### ISSUE TITLE
Un-covered resource service functions

### ISSUE THREAD

**Issue by rbs-jacob** [redballoonsecurity/ofrak#137]
PR #122 added two functions to the resource service (`delete_resources`, and `update_many`). But it does not seem to have added any tests to cover these functions. Tests should be added to cover them.

**Which files would be affected?**

- `ofrak_core/ofrak/service/resource_service.py`
- `ofrak_core/test_ofrak/service/resource_service/*.py`

**Does the proposed maintenance include non-doc string _functional_ changes to the Python code?**

Only adding tests.

**Are you interested in implementing it yourself?**

Perhaps

**Comment by whyitfor** [comment]
Closing as fixed as of 8ab2a86b4fbdb570e7a3d6bddb329f11f7ddc9b3: https://github.com/redballoonsecurity/ofrak/actions/runs/3833745233/jobs/6525501998.
