### ISSUE TITLE
OFRAK 2.2.1 incorrectly displays GUI version as 2.2.0

### ISSUE THREAD

**Issue by whyitfor** [redballoonsecurity/ofrak#251]
**What is the problem? (Here is where you provide a complete Traceback.)**
ofrak 2.2.1 from PyPI has the wrong version string in the GUI.

**Please provide some information about your environment.**
To reproduce:
```
% pip install ofrak
% ofrak gui
```
The version listed in bottom right of GUI is 2.2.0. It should be 2.2.1.

**If you've discovered it, what is the root cause of the problem?**
Possible that GUI wasn't rebuilt after https://github.com/redballoonsecurity/ofrak/pull/246.

**What are the steps to reproduce the issue?**
See above.

**How would you implement this fix?**
Probably should be addressed in a 2.2.2 release at some point.
Release process should also enforce rebuilding the GUI.

**Comment by EdwardLarson** [comment]
Fixed by a post-release to update the GUI files distributed via PyPI: https://pypi.org/project/ofrak/2.2.1.post1/
