### ISSUE TITLE
mac os install ???

### ISSUE THREAD

**Issue by pullghjunkkk** [redballoonsecurity/ofrak#348]
chikkachun@chikdeMBP ~ % git clone https://github.com/redballoonsecurity/ofrak.git
cd ofrak
Cloning into 'ofrak'...
remote: Enumerating objects: 5005, done.
remote: Counting objects: 100% (1728/1728), done.
remote: Compressing objects: 100% (525/525), done.
remote: Total 5005 (delta 1429), reused 1398 (delta 1203), pack-reused 3277
Receiving objects: 100% (5005/5005), 13.74 MiB | 7.13 MiB/s, done.
Resolving deltas: 100% (3345/3345), done.
chikkachun@chikdeMBP ofrak % ofrak list
zsh: command not found: ofrak
chikkachun@chikdeMBP ofrak % pip install ofrak
zsh: command not found: pip
chikkachun@chikdeMBP ofrak % git lfs install && git lfs pull
git: 'lfs' is not a git command. See 'git --help'.

The most similar commands are
	alias
	llg
	log
chikkachun@chikdeMBP ofrak % make develop
make: *** No rule to make target `develop'.  Stop.
chikkachun@chikdeMBP ofrak % ofrak_type
zsh: command not found: ofrak_type
chikkachun@chikdeMBP ofrak % ofrak deps --missing-only
zsh: command not found: ofrak
chikkachun@chikdeMBP ofrak % ofrak deps --packages-for brew | xargs brew install -y
zsh: command not found: ofrak
chikkachun@chikdeMBP ofrak % ls
build  dist  Dockerstub  LICENSE  Makefile  mypy.ini  ofrak_patch_maker  ofrak_patch_maker.egg-info  ofrak_patch_maker_test  setup.py  toolchain.conf.bak
$ cp toolchain.conf.bak toolchain.conf
CONTRIBUTING.md		frontend		ofrak_core
LICENSE			mkdocs.yml		ofrak_io
Makefile		ofrak-angr.yml		ofrak_patch_maker
README.md		ofrak-binary-ninja.yml	ofrak_tutorial
build_image.py		ofrak-core-dev.yml	ofrak_type
disassemblers		ofrak-dev.yml		pyproject.toml
docs			ofrak-ghidra.yml
examples		ofrak-tutorial.yml
zsh: command not found: build
zsh: command not found: $
chikkachun@chikdeMBP ofrak % cp toolchain.conf.bak toolchain.conf
cp: toolchain.conf.bak: No such file or directory
chikkachun@chikdeMBP ofrak % sudo make develop
cp toolchain.conf /etc/toolchain.conf
mv toolchain.conf toolchain.conf.bak
pip3 install -e .[test]
Obtaining file:///home/ofrak/ofrak/ofrak_patch_maker
Requirement already satisfied: immutabledict==2.2.0 in /usr/local/lib/python3.8/dist-packages (from ofrak-patch-maker==0.1.0) (2.2.0)
......
  Running setup.py develop for ofrak-patch-maker
Successfully installed ofrak-patch-maker
Password:
make: *** No rule to make target `develop'.  Stop.
cp: toolchain.conf: No such file or directory
mv: rename toolchain.conf to toolchain.conf.bak: No such file or directory
zsh: no matches found: .[test]
zsh: command not found: Obtaining
zsh: invalid mode specification
zsh: command not found: ......
zsh: command not found: Running
zsh: command not found: Successfully
chikkachun@chikdeMBP ofrak % git lfs install && git lfs pull.

git: 'lfs' is not a git command. See 'git --help'.

The most similar commands are
	alias
	llg
	log
chikkachun@chikdeMBP ofrak % git --help
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
chikkachun@chikdeMBP ofrak % git lfs install
git: 'lfs' is not a git command. See 'git --help'.

The most similar commands are
	alias
	llg
	log
chikkachun@chikdeMBP ofrak %

**Comment by ANogin** [comment]
@pullghjunkkk please follow the instructions in [`docs/environment-setup.md`](https://github.com/redballoonsecurity/ofrak/blob/master/docs/environment-setup.md) to install OFRAK. In particular:
- If installing using pip, you first need to install pip itself (and in turn, that requires installing Python first)
- If installing from source, you need to install git-lfs before you can clone, and you need to run `make develop` in appropriate subdirectories. 

For installing from source, #314 would hopefully make things a bit easier.
