### ISSUE TITLE
pip install for version 3.2.0 fails

### ISSUE THREAD

**Issue by csisl** [redballoonsecurity/ofrak#365]
**What is the problem?**

Installing version 3.2.0 fails with pip:

```
$ pip install ofrak==3.2.0
Collecting ofrak==3.2.0
  Using cached ofrak-3.2.0.tar.gz (6.4 MB)
Collecting ofrak_io==1.*,>=1.0
  Using cached ofrak_io-1.1.0-py3-none-any.whl
Collecting ofrak_type==2.*,>=2.2.0rc0
  Using cached ofrak_type-2.2.0.tar.gz (16 kB)
ERROR: Could not find a version that satisfies the requirement ofrak_patch_maker==4.*,>=4.0.2rc0 (from ofrak) (from versions: 0.0.1, 1.0.0, 2.0.0, 3.0.0, 4.0.0, 4.0.1)
ERROR: No matching distribution found for ofrak_patch_maker==4.*,>=4.0.2rc0
```

**Environment**

  - Platform: 
    - **macos and ubuntu**
  - Output of `python3 -m platform`.   
     - **macOS-13.3.1-arm64-arm-64bit**

**How often does the issue happen?**

For all installs on ubuntu + macos 

**What are the steps to reproduce the issue?**

`pip install ofrak==3.2.0`

Also, with `pip install ofrak`, the version of core that gets installed is version `3.1.0`

**Comment by rbs-jacob** [comment]
Hey, thanks for flagging this! Should be fixed. 

Feel free to reopen this (or another issue) if there are any other problems.
