### ISSUE TITLE
FreeSpaceModifier and PartialFreeSpace Modifier Improvements

### ISSUE THREAD

**Issue by andresito00** [redballoonsecurity/ofrak#37]
1) The modifiers should be consolidated.

2) The modifiers should _not_ require knowledge of instruction set architecture. We should opt for an ISA-agnostic `bytes`-based contract if any custom code should be used in replacement.

**Which files would be affected?**

- `ofrak_core/ofrak/core/free_space.py`
- `ofrak_core/ofrak/service/job_service.py`
- `ofrak_core/test_ofrak/unit/resource_view/test_view.py`

**Does the proposed maintenance include non-doc string _functional_ changes to the Python code?**
Yes

**Are you interested in implementing it yourself?**
Yes

**Comment by whyitfor** [comment]
I don't understand why the `FreeSpaceModifier` and `PartialFreeSpaceModifier` need to be consolidated.
