### ISSUE TITLE
Add support for El Torito ISO images

### ISSUE THREAD

**Issue by whyitfor** [redballoonsecurity/ofrak#56]
Many ISOs from the Internet are El Torito images, which are [currently not supported by the OFRAK ISO unpacker](https://github.com/redballoonsecurity/ofrak/blob/master/ofrak_components/ofrak_components/iso9660.py#L195).

Often the El Torito images will unpack successfully, but there are no tests for them, and it is not clear what more would need to be done to support them.

**What is the use case for the feature?**
Support unpacking and modifying El Torito images.

**Does the feature contain any proprietary information about another company's intellectual property?**
No.

**How would you implement this feature?**
Probably by extending current ISO support.

**Are there any (reasonable) alternative approaches?**

**Are you interested in implementing it yourself?**
No. This is a great first contributor issue!

**Comment by Tanmoy741127** [comment]
Hi can you assign this to me ?

**Comment by whyitfor** [comment]
Hi @Tanmoy741127, I've assigned you this issue.

Make sure to look at the [contributing guide](https://github.com/redballoonsecurity/ofrak/blob/master/docs/contributor-guide/getting-started.md). Thanks for your interest in helping out!

**Comment by rbs-jacob** [comment]
Fixed by #394.
