### ISSUE TITLE
make FilesystemRoot.initialize_from_disk() fail when given an incorrect path, instead of not initializing anything

### ISSUE THREAD

**Issue by whyitfor** [redballoonsecurity/ofrak#60]
**What is the problem? (Here is where you provide a complete Traceback.)**
The current code is essentially:
```
for root, dirs, files in os.walk(root_path):
    <something>
```
Which does nothing when root_path doesn't exist.

It also does nothing when the path given corresponds to a file and not a directory.

**Please provide some information about your environment.**
N/A

**If you've discovered it, what is the root cause of the problem?**
See above.

**How often does the issue happen?**
Whenever an incorrect path is passed to `FilesystemRoot.initialize_from_disk`.

**Are you interested in implementing it yourself?**
No. This is a good first contributor issue!

**Comment by galbwe** [comment]
Hi, can I work on this issue?

**Comment by jstrieb** [comment]
Hi @galbwe, go for it! Be sure to take a look at the [contributing guide](https://ofrak.com/docs/contributor-guide/getting-started.html).

Feel free to follow up with any questions in this thread.
